# Generated by Django 4.1.6 on 2023-02-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagen_posteo'),
        ),
    ]
